Adde xTB and xTB-GSM
ReactionMechanismGenerator/ARC pull request #536
Opened 2022-08-06 14:39 UTC by alongd

Added the xTB and xTB-GSM Job adapters.
This PR also includes an infrastructure for running these incore adapters, e.g., an internal ARC YAML format was implemented.

Note that torchANI is also added in this PR, yet knocked-out in subsequent commits due to environment issues. It's recommended to re-implement it and execute it as a sub-process in its own environment, utilizing the YAML format to store the output.

2022-08-06 18:45 UTC, kfir4444 requested changes
Hey @alongd, great job!
There are a few fixes, please see comments.
Note that although torchani is not included in this PR, there is a lot of preparations for it, I think you should maybe open an issue about it, with links to the relevant branches/commits, so that we will remember how to restart it if and when some time passes.

2022-08-06 18:45 UTC, kfir4444 commented on arc/common.py
> +    Copt a file safely.
Typo?

2022-08-06 18:45 UTC, kfir4444 commented on Makefile
> +# TorchANI is included in the arc_env, install_torchani.sh is not executed by ``make install-all``
Does ARC env include torchani after the change?

2022-08-06 18:45 UTC, kfir4444 commented on arc/job/adapters/__init__.py
> +# import arc.job.adapters.torch_ani
Can you clear this comment?

2022-08-06 18:45 UTC, kfir4444 commented on arc/job/adapters/gaussian.py
> +        execute_command(incore_commands[self.job_adapter])
Great fix!

2022-08-06 18:45 UTC, kfir4444 commented on arc/job/adapters/xtb_adapter.py
> +"""
Normally, the name of adapters is the `{software}.py`. For consistency, please rename.

2022-08-06 18:45 UTC, kfir4444 commented on devtools/install_torchani.sh
> +# Properly configure the shell to use 'conda activate'.
I wonder if installing torchani from the install file could have solved the issue we had before. Might worth a shot when we get back to it.

2022-08-06 18:45 UTC, kfir4444 commented on devtools/install_kinbot.sh
> +# Properly configure the shell to use 'conda activate'.
Another way could be `conda init bash`

2022-08-07 09:19 UTC, alongd commented
@kfir4444, all changes were performed, feel free to merge unless there are additional comments

2022-08-07 12:25 UTC, kfir4444 approved these changes

2022-08-07 12:25 UTC, merged