Tests: Added test_determine_symmetry to common tests
ReactionMechanismGenerator/ARC pull request #571
Opened 2022-12-02 03:50 UTC by alongd

The symmetry script (from the RMG qm module) was not tested in ARC. Added some simple tests.

2022-12-07 14:13 UTC, Laxzal requested changes

2022-12-07 14:13 UTC, Laxzal commented on arc/commonTest.py
> +        """Test the determine_symmetry() function"""
changes look good. the only thing I would like added is just a bit more explanation of the test.
inlcuding the phrase
""" Test the determine symmetry function"""
Also include about which the 3 tests in this function are doing and what you are expecting. I just think adding a bit more description will help when this test is run again in the future by someone else.

2022-12-11 04:42 UTC, alongd commented
Thanks, @Laxzal. Added and squashed.

2022-12-19 09:21 UTC, alongd commented
@Laxzal, I think we can merge this in once tests pass

2022-12-26 11:53 UTC, kfir4444 requested changes
Thanks @alongd!
I think the tests misses one case, where there are both symmetry and chirality. Could you add it?
Example: `CC=C=CC`

2022-12-28 04:57 UTC, alongd commented
Thanks for the suggestion, @kfir4444, added

2022-12-28 08:41 UTC, kfir4444 approved these changes
Thanks for addressing the comments @alongd,
approved and merged

2022-12-28 08:43 UTC, merged