Updating devtool installation
ReactionMechanismGenerator/ARC pull request #587
Opened 2023-01-01 08:04 UTC by Laxzal

devtool bash scripts search for mamba, and if found, will use mamba as the installation command.

2023-01-01 12:58 UTC, kfir4444 requested changes
Thanks @Laxzal!
I have some comments/questions, could you address them?

2023-01-01 12:58 UTC, kfir4444 commented on devtools/install_autotst.sh
> +if [ $(mamba) ] > /dev/null 2>&1; then
Can you explain this line to me?

2023-01-01 12:58 UTC, kfir4444 commented on devtools/install_autotst.sh
> +	echo "mamba found"
What if the user doesn't have both?

2023-01-01 13:04 UTC, Laxzal commented on devtools/install_autotst.sh
> +if [ $(mamba) ] > /dev/null 2>&1; then
It's just a redirection line. 
/dev/null accepts and discards all input;
2>&1 merges output from stream 2 with stream 1

So basically I am telling the system that it doesn't need to report anything in the terminal to the user

2023-01-01 13:29 UTC, Laxzal commented on devtools/install_autotst.sh
> +	echo "mamba found"
I guess you could echo that they are missing an installation command but I think they would run into this error when it cannot install anyway. 

Further, maybe we should add to the website instructions to just tell them to install anaconda or mambaforge

2023-01-11 13:12 UTC, kfir4444 reviewed
Thanks @Laxzal!
One quick comment

2023-01-11 13:12 UTC, kfir4444 commented on devtools/install_sella.sh
> +
Can you remove some of these empty lines?

2023-01-13 06:53 UTC, kfir4444 approved these changes
Thanks @Laxzal! Great job!

2023-01-13 06:54 UTC, merged