Openbabel
ReactionMechanismGenerator/ARC pull request #601
Opened 2023-02-19 09:58 UTC by kfir4444

This PR adds a OpenBabel Job adapter for opt/sp jobs

2023-02-20 05:56 UTC, alongd reviewed
Perfect, thanks for this addition!!
Please see some comments

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/obabel.py
> +        if self.level.method is not None:
Can this adapter be called with `self.level.method` set to `None`? If so, how would ARC know to run this adapter?

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/obabel.py
> +            ob_default_settigns["FF"] = self.level.method
I think this is repetitive with what we have under `write_input_file`

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/obabel.py
> +            logger.error(f'Given wrong settings in input: {ob_default_settigns}\n'
I think we should raise an error here, not just log an error

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +        save_output_file(path = str(args.yml_path), key="opt_xyz", val=opt_xyz)
Can you check whether `args.yml_path` is a string or a list? I think it usually returns a list, and we should do something like `args.yml_path[0]` to access the content

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +        save_output_file(path = str(args.yml_path), key="opt_xyz", val=opt_xyz)
Can you check whether `args.yml_path` is a string or a list? I think it usually returns a list, and we should do something like `args.yml_path[0]` to access the content

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +        val (Union[float, dict, np.ndarray], optional): The value to be stored.
YAML file are infamouse for their treatment of np value types
I suggest to make sure not to pass `np.ndarray` here, or to convert it inside the function

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +    if content_dict is not None:
Can `content_dict` be `None` after the above line? Did you mean to check whether it's not an empty dict?

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +                   content: list,
looks line content is a dict

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +def unconstraint_opt(mol: openbabel.OBMol,
I wonder if the two opt functions can be merged (and called through one directive in `main`) for better maintainability

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +    energy = ff.Energy()*4.18 # kcal/mol to kj/mol
maybe use 4.184 which is a bit more exact? (although FF energies are not accurate anyway, but why not)

2023-02-20 05:56 UTC, alongd commented on devtools/install_ob.sh
> +$COMMAND_PKG env create -n ob_env conda-forge::openbabel
we should add YAML to this env

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/obabel_test.py
> + 'xyz': '9\n'
You could use a multiline string `"""` to make sections like that more readable

2023-02-20 05:56 UTC, alongd commented on arc/job/adapters/__init__.py
> +import arc.job.adapters.obabel
can you squash this commit into the original change?

2023-02-20 08:20 UTC, Laxzal requested changes

2023-02-20 08:20 UTC, Laxzal commented on arc/job/adapters/obabel.py
> +from arc.settings.settings import ob_default_settigns
This needs to be fixed from `ob_default_settigns` to `ob_default_settings`

2023-02-20 08:20 UTC, Laxzal commented on arc/job/adapters/scripts/ob_script.py
> +        save_output_file(path = str(args.yml_path), key="opt_xyz", val=opt_xyz)
I believe it will be a string due to how Kfir has set the function `parse_command_line_arguments()`

2023-02-20 08:20 UTC, Laxzal commented on arc/job/adapters/scripts/ob_script.py
> +        val (Union[float, dict, np.ndarray], optional): The value to be stored.
Small point but I think we should also set the parameters in the function to be the type as described in the function doc string.

2023-02-20 15:12 UTC, kfir4444 commented on arc/job/adapters/obabel.py
> +        if self.level.method is not None:
with API maybe?

2023-02-20 15:21 UTC, kfir4444 commented on arc/job/adapters/scripts/ob_script.py
> +        val (Union[float, dict, np.ndarray], optional): The value to be stored.
This comes from here:
https://github.com/ReactionMechanismGenerator/ARC/blob/2a980e511f9b422fe867865c617809727be0cdd4/arc/job/adapter.py#L1317
I try to avoid using type hinting in the scripts because they sometime requires additional imports, and are not as important in this case.

2023-02-20 15:28 UTC, kfir4444 commented on devtools/install_ob.sh
> +$COMMAND_PKG env create -n ob_env conda-forge::openbabel
No, it's distributed with ob probably

2023-02-21 11:58 UTC, alongd reviewed
Looking good, added two minor comments

2023-02-21 11:58 UTC, alongd commented on arc/job/adapters/scripts/ob_script.py
> +def unconstraint_opt(mol: openbabel.OBMol,
I recommend to consolidate the functions into a single call. Then if constraint opt is requested, call another function to initialize the params, then continue either way with a similar workflow

2023-02-21 11:58 UTC, alongd commented on devtools/install_ob.sh
> +$COMMAND_PKG env create -n ob_env conda-forge::openbabel
Could you check?

2023-02-27 08:11 UTC, Laxzal approved these changes
Looks good to me

2023-02-27 08:36 UTC, merged