Fix env
ReactionMechanismGenerator/ARC pull request #652
Opened 2023-05-09 08:05 UTC by kfir4444

This PR contains two features:

1. An update to the ARC environment, specifically numpy and cantera version update, and removal of nosetests, which is deprecated
2. replacing the `@wip` decorator with a one that is not dependent on nosetests.

2023-05-09 09:00 UTC, alongd commented on environment.yml
> +  - cantera::cantera=2.6
maybe `>=`?

2023-05-13 07:34 UTC, kfir4444 commented
> Do you think we should bump numpy more? See #517
Probably not possible for now, we would need to update python:
  ├─ numpy 1.22.0**  is installable with the potential options
  │  ├─ numpy 1.22.0 would require
  │  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
  │  ├─ numpy 1.22.0 would require
  │  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
  │  └─ numpy 1.22.0 would require
  │     └─ python >=3.8,<3.9.0a0 , which can be installed;
  └─ python 3.7**  is uninstallable because there are no viable options
     ├─ python [3.7.0|3.7.1|...|3.7.9] conflicts with any installable versions previously reported;
     └─ python 3.7.1 would require
        └─ openssl >=1.1.1,<1.1.2.0a0 , which does not exist (perhaps a missing channel).

2023-05-13 10:48 UTC, calvinp0 requested changes
Everything looks good to me with the exception of the minor pedantic removal of certain paths when looking for xtb

2023-05-13 10:48 UTC, calvinp0 commented on arc/settings/settings.py
>  paths.append(os.path.join(home, 'anaconda3', 'envs', 'arc_env', 'bin', 'xtb'))
With the removal of xtb from arc_env, I think we need to remove the path appends that include the arc_env

2023-05-13 12:56 UTC, alongd commented on arc/settings/settings.py
> +                            'xtb_env', 'bin', 'python')
why was this  changed ?

2023-05-13 14:17 UTC, calvinp0 commented on arc/settings/settings.py
> +                            'xtb_env', 'bin', 'python')
That was my mistake. It was during the xTB issue. Changing it back

2023-05-13 19:29 UTC, alongd submitted a review, later dismissed
Looking good!
I don't support locking dependable versions using a `=`, I do think we should allow `>=`
Other than that it's good to go

2023-05-14 04:38 UTC, alongd approved these changes

2023-05-14 04:38 UTC, alongd commented
Are we clear to merge?

2023-05-14 05:09 UTC, calvinp0 approved these changes

2023-05-14 05:09 UTC, merged