Improved TS energy checks
ReactionMechanismGenerator/ARC pull request #690
Opened 2023-08-03 07:59 UTC by alongd

Calling the checks from a centralized function
Refactoring ts_check functions
Tests added

2023-08-22 07:28 UTC, kfir4444 requested changes
Hey @alongd thanks for this PR!
I have added some comments.

2023-08-22 07:28 UTC, kfir4444 commented on arc/checks/ts.py
>      if verbose:
Note that this is the third `if verbose` in this function. Could you please unify them?

2023-08-22 08:19 UTC, alongd commented on arc/scheduler.py
> +            if label in labels and rxn.ts_species.ts_checks['E0'] is None \
Right, this is just semantics, not logic. I think the current version is more explicit.

2023-08-22 08:27 UTC, alongd commented
Thanks, @kfir4444, I addressed the comments with fixup commits, let me know if you have additional comments or whether I can go ahead and squash

2023-08-22 08:42 UTC, kfir4444 commented on arc/checks/ts.py
>      if verbose:
I agree, if there is a return between them then it will exit the function, and there is no need for 3 of them, right?

2023-08-23 09:02 UTC, alongd commented on arc/checks/ts.py
> +            return
return

2023-10-02 09:27 UTC, kfir4444 approved these changes

2023-10-02 09:27 UTC, merged