Added a module for working with RMG reaction families
ReactionMechanismGenerator/ARC pull request #754
Opened 2024-07-02 09:15 UTC by alongd

Now we can identify for each ARC reaction all possible pathways between the reactants and products according to reaction families supported by RMG.
Also added dummy ARC families (w/o kinetics) to assist in identifying reaction templates.
Tests added.

2025-03-17 07:27 UTC, LeenFahoum approved these changes

2025-03-17 07:36 UTC, LeenFahoum submitted a review, later dismissed

2025-03-17 08:58 UTC, kfir4444 commented on arc/species/species_test.py
> +
I don't think we need the extra line here

2025-03-17 09:00 UTC, kfir4444 commented on arc/mapping/engine.py
> +            candidate = None
I don't think this is required, since it's in the for loop anyway

2025-03-17 10:06 UTC, kfir4444 commented on data/families/hydrolysis.py
> +name = "hydrolysis/groups"
Is this specifically related to the topic of this PR? if not, I think it should become a separate PR.

2025-03-17 10:11 UTC, calvinp0 commented on arc/processor.py
> +import math
Remove the import

2025-03-17 10:17 UTC, calvinp0 requested changes

2025-03-17 10:17 UTC, calvinp0 commented on .github/workflows/cont_int.yml
> +        fail_ci_if_error: false
Add extra line

2025-03-17 10:20 UTC, kfir4444 commented on arc/reaction/reaction.py
> +            self.rmg_reaction_from_arc_species()  # needed?
Please determine if we need this or remove the comment

2025-03-17 10:21 UTC, kfir4444 commented on arc/reaction/reaction_test.py
> +        # if not rxn.family:  # reaction family not found for some reason.
Please remove comments

2025-03-17 10:31 UTC, calvinp0 commented on arc/family/family.py
> +def add_labels_to_molecule(mol: 'Molecule',   # revisit, copilot, and test
Is the comment still relevant?

2025-03-17 10:32 UTC, calvinp0 commented on arc/family/family_test.py
> +                     ARCSpecies(label="P2", smiles="N[NH]", is_ts=False, multiplicity=2, charge=0)]  # todo: make this pass, retest H abstraction heuristics
Remove comment if completed

2025-03-17 10:32 UTC, calvinp0 commented on arc/family/family_test.py
> +            self.assertTrue(any([mol.is_isomorphic(water) for mol in prod_list[0]]))  # continue fixing tests, your on thwe right path, then implement this atom label map in functions
Remove comment if not relevant anymore

2025-03-18 14:06 UTC, alongd commented
@LeenFahoum @calvinp0 @kfir4444 
Thanks all for your comments
Most comments were addressed with fixup commits, some comments about modifications deep in the commits were already squashed
Please take a look, and let me know if OK to squash the fixups

2025-03-18 21:44 UTC, calvinp0 approved these changes
LGTM

2025-03-19 09:45 UTC, LeenFahoum approved these changes

2025-03-22 21:21 UTC, alongd commented
Thanks! Fixups are squashed, please merge if there aren't any further comments

2025-03-23 17:11 UTC, merged